// Obsidian-style graph view for the 한국어 vault.
//
// Data source: window.VAULT_GRAPH (generated by tools/build-graph.py from a
// Webpage HTML Export). If that file is absent or empty, the placeholder
// sample below is shown instead.
//
// Interactions: drag nodes · scroll to zoom · drag background to pan ·
// click a node to open the note (resolved notes only) · hover for details.

window.PLACEHOLDER_GRAPH = {
  nodes: [
    { id: "root", label: "한국어", group: "topic", deg: 4 },
    { id: "vocab-topic", label: "어휘", group: "topic", deg: 3 },
    { id: "grammar-topic", label: "문법", group: "topic", deg: 3 },
    { id: "v1", label: "안녕하세요", gloss: "hello (formal)", group: "vocab", deg: 1 },
    { id: "v2", label: "감사합니다", gloss: "thank you", group: "vocab", deg: 1 },
    { id: "v3", label: "사랑", gloss: "love (n.)", group: "vocab", deg: 2 },
    { id: "v4", label: "가다", gloss: "to go", group: "vocab", deg: 3 },
    { id: "v5", label: "먹다", gloss: "to eat", group: "vocab", deg: 2 },
    { id: "v6", label: "괜찮아요", gloss: "it's okay", group: "vocab", deg: 2 },
    { id: "g1", label: "-는데", gloss: "background / contrast", group: "grammar", deg: 2 },
    { id: "g2", label: "-아/어서", gloss: "reason / sequence", group: "grammar", deg: 2 },
    { id: "g3", label: "-(으)ㄹ 것 같다", gloss: "I think / it seems", group: "grammar", deg: 2 },
    { id: "g4", label: "-고 있다", gloss: "present progressive", group: "grammar", deg: 3 },
  ],
  links: [
    { source: "root", target: "vocab-topic" }, { source: "root", target: "grammar-topic" },
    { source: "vocab-topic", target: "v1" }, { source: "vocab-topic", target: "v2" },
    { source: "vocab-topic", target: "v3" }, { source: "vocab-topic", target: "v4" },
    { source: "vocab-topic", target: "v5" }, { source: "vocab-topic", target: "v6" },
    { source: "grammar-topic", target: "g1" }, { source: "grammar-topic", target: "g2" },
    { source: "grammar-topic", target: "g3" }, { source: "grammar-topic", target: "g4" },
    { source: "v4", target: "g4" }, { source: "v5", target: "g4" },
    { source: "v4", target: "g2" }, { source: "v3", target: "g3" }, { source: "v6", target: "g1" },
  ],
};

(function initGraph() {
  const wrap = document.getElementById("graph-wrap");
  const svg = document.getElementById("graph-svg");
  const tooltip = document.getElementById("graph-tooltip");
  const legendEl = document.getElementById("graph-legend");
  const countEl = document.getElementById("node-count");
  if (!wrap || !svg) return;

  const usingVault = !!(window.VAULT_GRAPH && window.VAULT_GRAPH.nodes && window.VAULT_GRAPH.nodes.length);
  const data = usingVault ? window.VAULT_GRAPH : window.PLACEHOLDER_GRAPH;

  const svgNS = "http://www.w3.org/2000/svg";
  let clientW = wrap.clientWidth;
  let clientH = wrap.clientHeight;

  // --- colors per group ---
  const PALETTE = ["#1e407c", "#6b93d6", "#d9a900", "#7c6bb0", "#3f8f7a", "#c46a4f", "#8a6d3b", "#4d7ea8"];
  const MISSING_COLOR = "#b9c2d0";
  const groupOrder = [];
  data.nodes.forEach(n => {
    if (!n.missing && !groupOrder.includes(n.group)) groupOrder.push(n.group);
  });
  const colorOf = n => n.missing ? MISSING_COLOR : PALETTE[groupOrder.indexOf(n.group) % PALETTE.length];

  // --- legend + count ---
  if (legendEl) {
    const parts = groupOrder.map((g, i) =>
      `<span><span class="dot" style="background:${PALETTE[i % PALETTE.length]}"></span>${g}</span>`);
    if (data.nodes.some(n => n.missing)) {
      parts.push(`<span><span class="dot" style="background:${MISSING_COLOR}"></span>unresolved (not in export)</span>`);
    }
    legendEl.innerHTML = parts.join("");
  }
  if (countEl) {
    countEl.textContent = `${data.nodes.length} nodes · ${data.links.length} links` +
      (usingVault ? ` · ${data.source}` : " · sample data");
  }

  // --- simulation state ---
  const nodes = data.nodes.map((n, i) => {
    const angle = (i / data.nodes.length) * Math.PI * 2;
    const radius = Math.min(clientW, clientH) * 0.3 + (i % 5) * 14;
    return {
      ...n,
      r: Math.max(5, Math.min(16, 5 + 2 * Math.sqrt(n.deg || 1))),
      x: clientW / 2 + Math.cos(angle) * radius,
      y: clientH / 2 + Math.sin(angle) * radius,
      vx: 0, vy: 0,
    };
  });
  const nodeById = Object.fromEntries(nodes.map(n => [n.id, n]));
  const links = data.links
    .filter(l => nodeById[l.source] && nodeById[l.target])
    .map(l => ({ source: nodeById[l.source], target: nodeById[l.target] }));

  // --- viewBox camera (zoom / pan) ---
  const vb = { x: 0, y: 0, w: clientW, h: clientH };
  let userMoved = false;   // stop auto-fitting once the user takes over
  const applyVB = () => svg.setAttribute("viewBox", `${vb.x} ${vb.y} ${vb.w} ${vb.h}`);
  const toWorld = (px, py) => ({ x: vb.x + (px / clientW) * vb.w, y: vb.y + (py / clientH) * vb.h });

  function autoFit() {
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    nodes.forEach(n => {
      minX = Math.min(minX, n.x); maxX = Math.max(maxX, n.x);
      minY = Math.min(minY, n.y); maxY = Math.max(maxY, n.y);
    });
    const pad = 70;
    minX -= pad; minY -= pad; maxX += pad; maxY += pad;
    let w = maxX - minX, h = maxY - minY;
    const aspect = clientW / clientH;
    if (w / h < aspect) { const nw = h * aspect; minX -= (nw - w) / 2; w = nw; }
    else { const nh = w / aspect; minY -= (nh - h) / 2; h = nh; }
    vb.x = minX; vb.y = minY; vb.w = w; vb.h = h;
    applyVB();
  }

  // --- build SVG elements ---
  const linkEls = links.map(() => {
    const line = document.createElementNS(svgNS, "line");
    line.setAttribute("stroke", "rgba(30,64,124,0.25)");
    line.setAttribute("stroke-width", "1");
    svg.appendChild(line);
    return line;
  });

  const nodeGroups = nodes.map(n => {
    const g = document.createElementNS(svgNS, "g");
    g.style.cursor = n.url ? "pointer" : "grab";

    const glow = document.createElementNS(svgNS, "circle");
    glow.setAttribute("r", n.r + 5);
    glow.setAttribute("fill", colorOf(n));
    glow.setAttribute("opacity", n.missing ? "0.08" : "0.14");
    g.appendChild(glow);

    const circle = document.createElementNS(svgNS, "circle");
    circle.setAttribute("r", n.r);
    circle.setAttribute("fill", colorOf(n));
    circle.setAttribute("opacity", n.missing ? "0.55" : "1");
    circle.setAttribute("stroke", "#ffffff");
    circle.setAttribute("stroke-width", "2");
    g.appendChild(circle);

    const text = document.createElementNS(svgNS, "text");
    text.setAttribute("text-anchor", "middle");
    text.setAttribute("y", n.r + 14);
    text.setAttribute("fill", n.missing ? "#8a93a6" : "#33415c");
    text.setAttribute("font-size", "11");
    text.setAttribute("font-family", "Noto Sans KR, sans-serif");
    text.style.pointerEvents = "none";
    text.textContent = n.label;
    g.appendChild(text);

    svg.appendChild(g);
    return g;
  });

  // --- physics with cool-down ---
  let alpha = 1;
  let running = false;
  let draggingNode = null;

  function step() {
    for (let i = 0; i < nodes.length; i++) {
      for (let j = i + 1; j < nodes.length; j++) {
        const a = nodes[i], b = nodes[j];
        let dx = a.x - b.x, dy = a.y - b.y;
        let d2 = dx * dx + dy * dy || 0.01;
        if (d2 < 90000) {  // skip far pairs
          const d = Math.sqrt(d2);
          const f = (1400 / d2) * alpha;
          const fx = (dx / d) * f, fy = (dy / d) * f;
          a.vx += fx; a.vy += fy;
          b.vx -= fx; b.vy -= fy;
        }
      }
    }
    links.forEach(l => {
      let dx = l.target.x - l.source.x, dy = l.target.y - l.source.y;
      let d = Math.sqrt(dx * dx + dy * dy) || 0.01;
      const f = (d - 85) * 0.025 * alpha;
      const fx = (dx / d) * f, fy = (dy / d) * f;
      l.source.vx += fx; l.source.vy += fy;
      l.target.vx -= fx; l.target.vy -= fy;
    });
    const cx = clientW / 2, cy = clientH / 2;
    nodes.forEach(n => {
      if (n === draggingNode) return;
      n.vx += (cx - n.x) * 0.0012 * alpha;
      n.vy += (cy - n.y) * 0.0012 * alpha;
      n.vx *= 0.85; n.vy *= 0.85;
      n.x += n.vx; n.y += n.vy;
    });

    linkEls.forEach((line, i) => {
      line.setAttribute("x1", links[i].source.x);
      line.setAttribute("y1", links[i].source.y);
      line.setAttribute("x2", links[i].target.x);
      line.setAttribute("y2", links[i].target.y);
    });
    nodeGroups.forEach((g, i) => {
      g.setAttribute("transform", `translate(${nodes[i].x}, ${nodes[i].y})`);
    });

    if (!userMoved) autoFit();
    alpha *= 0.992;
    if (alpha > 0.02 || draggingNode) {
      requestAnimationFrame(step);
    } else {
      running = false;
    }
  }

  function kick(a) {
    alpha = Math.max(alpha, a);
    if (!running) { running = true; requestAnimationFrame(step); }
  }

  // --- pointer helpers ---
  function localPoint(evt) {
    const rect = wrap.getBoundingClientRect();
    const cx = evt.touches ? evt.touches[0].clientX : evt.clientX;
    const cy = evt.touches ? evt.touches[0].clientY : evt.clientY;
    return { x: cx - rect.left, y: cy - rect.top };
  }

  // --- node interactions: drag, click-to-open, tooltip ---
  nodeGroups.forEach((g, i) => {
    const n = nodes[i];
    let downAt = null;

    const start = (evt) => {
      evt.stopPropagation();
      evt.preventDefault();
      draggingNode = n;
      downAt = localPoint(evt);
      userMoved = true;
      kick(0.4);
    };
    g.addEventListener("mousedown", start);
    g.addEventListener("touchstart", start, { passive: false });

    g.addEventListener("mouseup", (evt) => {
      if (!downAt) return;
      const p = localPoint(evt);
      const moved = Math.hypot(p.x - downAt.x, p.y - downAt.y);
      if (moved < 5 && n.url) window.open(n.url, "_blank");
      downAt = null;
    });

    const showTip = (evt) => {
      if (!tooltip) return;
      const p = localPoint(evt);
      tooltip.style.left = p.x + "px";
      tooltip.style.top = p.y + "px";
      const detail = n.gloss ? n.gloss :
        (n.missing ? n.group + " · not in export" : n.group + (n.url ? " · click to open" : ""));
      tooltip.innerHTML = `<span class="kr">${n.label}</span>${detail}`;
      tooltip.style.opacity = "1";
    };
    g.addEventListener("mouseenter", showTip);
    g.addEventListener("mousemove", showTip);
    g.addEventListener("mouseleave", () => { if (tooltip) tooltip.style.opacity = "0"; });
  });

  // --- background pan ---
  let panFrom = null;
  svg.addEventListener("mousedown", (evt) => {
    panFrom = localPoint(evt);
    userMoved = true;
  });
  svg.addEventListener("touchstart", (evt) => {
    if (evt.touches.length === 1 && !draggingNode) {
      panFrom = localPoint(evt);
      userMoved = true;
    }
  }, { passive: true });

  const move = (evt) => {
    const p = localPoint(evt);
    if (draggingNode) {
      const w = toWorld(p.x, p.y);
      draggingNode.x = w.x; draggingNode.y = w.y;
      draggingNode.vx = 0; draggingNode.vy = 0;
      kick(0.25);
      if (evt.cancelable) evt.preventDefault();
    } else if (panFrom) {
      vb.x -= (p.x - panFrom.x) * (vb.w / clientW);
      vb.y -= (p.y - panFrom.y) * (vb.h / clientH);
      panFrom = p;
      applyVB();
    }
  };
  const end = () => { draggingNode = null; panFrom = null; };
  window.addEventListener("mousemove", move);
  window.addEventListener("touchmove", move, { passive: false });
  window.addEventListener("mouseup", end);
  window.addEventListener("touchend", end);

  // --- wheel zoom (about the cursor) ---
  wrap.addEventListener("wheel", (evt) => {
    evt.preventDefault();
    userMoved = true;
    const factor = evt.deltaY > 0 ? 1.12 : 1 / 1.12;
    const scale = clientW / (vb.w * factor);
    if (scale < 0.04 || scale > 8) return;
    const p = localPoint(evt);
    const w = toWorld(p.x, p.y);
    vb.x = w.x - (w.x - vb.x) * factor;
    vb.y = w.y - (w.y - vb.y) * factor;
    vb.w *= factor; vb.h *= factor;
    applyVB();
  }, { passive: false });

  window.addEventListener("resize", () => {
    clientW = wrap.clientWidth;
    clientH = wrap.clientHeight;
    if (!userMoved) autoFit();
  });

  applyVB();
  kick(1);
})();
